spring.application.name=pokedex

# set port 3333
server.port=3333

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/pokedex}
spring.datasource.username=${DB_USERNAME:pokedex}
spring.datasource.password=${DB_PASSWORD:pokedex}
spring.datasource.driver-class-name=org.postgresql.Driver

# Show all logs for debugging purposes
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.example.pokedex=DEBUG

# Show SQL statements in the logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true