services:
  postgresPokeCenter:
    image: postgres:16-alpine
    container_name: pokecenter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: pokedex
      POSTGRES_PASSWORD: pokedex
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pokedex -d pokedex" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
